### ISSUE TITLE
Need to cache API requests to speed up program and lower API requests

### ISSUE THREAD

**Issue by jordangerdin** [jordangerdin/Camping-API#2]
Should implement requests-cache on coordinates by city, and hiking trails by coordinates.

Images and weather not necessary to cache for now.

https://pypi.org/project/requests-cache/

**Comment by jordangerdin** [comment]
Current GUI branch uses global dictionary to store data, should be replaced with requests-cache

**Comment by azhdrake** [comment]
We decided against doing this.
