### ISSUE TITLE
Add bookmark database

### ISSUE THREAD

**Issue by azhdrake** [jordangerdin/Camping-API#5]
We need a database so that users can save their favorite trails.

**Comment by jordangerdin** [comment]
Data saved to bookmark database should be

- ID
- Trail name
- Type
- Difficulty
- Stars
- Location
- Length
- Ascent
- Descent
- Condition Details
- URL

**Comment by jordangerdin** [comment]
Database will use Peewee, using the MVVM structure.

**Comment by jordangerdin** [comment]
#9 Database created and merged.
